version: "2.4"
networks:
  python_services:
    name: python_services
    driver: bridge

services:

  elasticsearch:
    image: elasticsearch:7.14.0
    container_name: elasticsearch
    networks:
      - python_services
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms1G -Xmx1G
    healthcheck:
      test: [ "CMD","curl", "-XGET" , "elasticsearch:9200/reports" ]
      interval: 20s
      timeout: 20s
      retries: 5


  mongo:
    image: mongo:latest
    container_name: mongo
    networks:
      - python_services
    ports:
      - "27017:27017"

  python:
    container_name: python
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mongo:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    ports:
      - "8082:8082"
    networks:
      - python_services

